### ISSUE TITLE
Missing env vars in strict mode

### ISSUE THREAD

**Issue by cbmdfc** [patrickdappollonio/dotenv#12]
hello Patrick,,,

there are some missing env vars that break my scripts on strict mode, can you add

* `PWD` and maybe `OLDPWD` but `PWD` is enoug
* `LOGNAME` in older situations this is preferred over `USER`
* `EDITOR` and/or `VISUAL` for edits and pagers so i can run something similar to `crontab -e`
* `DISPLAY` to run a X-11 based screen
* `HOSTNAME` since some of my scripts reference it

**Comment by patrickdappollonio** [comment]
Hey Ivan, good to see you around this repo too! 😜

These sound all like good ideas. Since they're all passthrough I'm okay adding them all.
